name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Fix permissions
      run: sudo chmod -R 777 /github/workspace
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fluentd-azure-inf:$(date +%s)
